version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 weather_site.wsgi:application
    environment:
      DEBUG: "False"
      SECRET_KEY: "your-secret-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1,yourdomain.com"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: